#!/bin/bash
cd src
echo '#include "mezzanine.h"' > scriptbindinglua51.cpp
echo '#include <Ogre.h>' >> scriptbindinglua51.cpp
echo '#include "btBulletDynamicsCommon.h"' >> scriptbindinglua51.cpp
echo '#include <cAudio.h>' >> scriptbindinglua51.cpp
echo '/// @file' >> scriptbindinglua51.cpp
echo '/// @brief This file has the interface for the Lua based implementation of the Scripting system.' >> scriptbindinglua51.cpp
echo '/// @details This file is mostly automatically generated by SWIG 2.0. What is not made by is' >> scriptbindinglua51.cpp
echo '/// created the BuildLuaBindingsOnLinux shell script' >> scriptbindinglua51.cpp
echo '' >> scriptbindinglua51.cpp
echo '// We really should not document this file to much more, it would be like making an atlas of the clouds.' >> scriptbindinglua51.cpp
echo '/// @cond 0'>> scriptbindinglua51.cpp
echo '' >> scriptbindinglua51.cpp

swig2.0 -c++ -v -Wall -lua -includeall -o scriptbindinglua51.cpp.tmp mezzanine.h
cat scriptbindinglua51.cpp.tmp >> scriptbindinglua51.cpp
rm scriptbindinglua51.cpp.tmp
mv scriptbindinglua51.cpp Scripting/Lua51/


echo '' >> scriptbindinglua51.cpp
echo '/// @endcond' >> scriptbindinglua51.cpp
