#!/bin/bash

ARGCOUNT=3
E_WRONGARGS=70
E_FILE_NOT_EXIST=71
E_TARGET_EXISTS=72

if [ $# -ne "$ARGCOUNT" ]
then
  echo "Usage: $0 FileNameWithoutExtension NewfileNameWithoutExtension Comment"
  exit $E_WRONGARGS
fi  

#If any of the targets exist we need to exit
if [ -e "$2.aif" ]
then
  echo "Target File \""$2.aif"\" already exists."
  exit $E_TARGET_EXISTS
fi
if [ -e "$2.wav" ]
then
  echo "Target File \""$2.wav"\" already exists."
  exit $E_TARGET_EXISTS
fi
if [ -e "$2.mp3" ]
then
  echo "Target File \""$2.mp3"\" already exists."
  exit $E_TARGET_EXISTS
fi

#Check to see if the files to be renamed exist
if [ ! -e "$1.aif" ]
then
  echo "File \""$1.aif"\" does not exist."
  exit $E_FILE_NOT_EXIST
fi  
if [ ! -e "$1.wav" ]
then
  echo "File \""$1.wav"\" does not exist."
  exit $E_FILE_NOT_EXIST
fi  
if [ ! -e "$1.mp3" ]
then
  echo "File \""$1.mp3"\" does not exist."
  exit $E_FILE_NOT_EXIST
fi  

#Lets move the files with and alert git at the same time
git mv "$1.aif" $2.aif
git mv "$1.wav" $2.wav
git mv "$1.mp3" $2.mp3

#Update the Manifest with the new information
echo "$2	aif,wav,mp3	$3" >> SoundManifest.txt
