//© Copyright 2010 BlackTopp Studios Inc.
/* This file is part of The PhysGame Engine.

    The PhysGame Engine is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The PhysGame Engine is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with The PhysGame Engine.  If not, see <http://www.gnu.org/licenses/>.
*/
/* The original authors have included a copy of the license specified above in the
   'Docs' folder. See 'gpl.txt'
*/
/* We welcome the use of The PhysGame anyone, including companies who wish to
   Build professional software and charge for their product.

   However there are some practical restrictions, so if your project involves
   any of the following you should contact us and we will try to work something
   out:
    - DRM or Copy Protection of any kind(except Copyrights)
    - Software Patents You Do Not Wish to Freely License
    - Any Kind of Linking to Non-GPL licensed Works
    - Are Currently In Violation of Another Copyright Holder's GPL License
    - If You want to change our code and not add a few hundred MB of stuff to
        your distribution

   These and other limitations could cause serious legal problems if you ignore
   them, so it is best to simply contact us or the Free Software Foundation, if
   you have any questions.

   Joseph Toppi - toppij@gmail.com
   John Blackwood - makoenergy02@gmail.com
*/
#ifndef _uimenuwindow_h
#define _uimenuwindow_h

#include "uiwindow.h"

#include <vector>
#include <utility>

namespace phys
{
    namespace UI
    {
        class UIlayer;
        class Menu;
        ///////////////////////////////////////////////////////////////////////////////
        /// @class MenuWindow
        /// @headerfile uimenuwindow.h
        /// @brief This class is an extended version of the window class for use exclusively with the menu widget.
        /// @details
        ///////////////////////////////////////
        class MenuWindow : public Window
        {
            protected:
                MenuWindow* ParentWindow;
                UI::Menu* MasterMenu;
                Button* BackButton;
                std::vector<std::pair<Button*,MenuWindow*> > ChildWindows;
            public:
                /// @brief Standard initialization constructor.
                /// @param Name The name of the window.
                /// @param Position The position of the window.
                /// @param Size The size of the window.
                /// @param TheMenu The menu this window belongs to.
                /// @param Layer The parent layer this window belongs to.
                MenuWindow(ConstString& Name, Vector2 Position, Vector2 Size, UI::Menu* TheMenu, UILayer* Layer);
                /// @brief Standard destructor.
                virtual ~MenuWindow();
                /// @brief Gets the parent window of this window.
                /// @return Returns a pointer to the parent window of this window, or NULL if this is the root window.
                virtual MenuWindow* GetParentWindow();
                /// @brief Creates a back button for this window.
                /// @details The name is autogenerated to be the name of the window + "back".
                /// This function will do nothing if the back button has already been created.
                /// @return Returns a pointer to the created Back Button.
                virtual Button* CreateBackButton(Vector2 Position, Vector2 Size);
                /// @brief Gets the back button of this window.
                /// @return Returns a pointer to the Back Button, or NULL if it hasn't been created.
                virtual Button* GetBackButton();
                /// @brief Gets the Window corresponding to the access button.
                /// @param Accessor Pointer to the Button of which you want to get the window for.
                /// @return Returns A pointer to the Menu window the button provided accesses.
                virtual MenuWindow* GetWindowOfAccessButton(Button* Accessor);
                /// @brief Adds a child window to this window.
                /// @details The name provided will become the windows name, the accompanying button will be the
                /// same +"button".
                /// @param Name The name of the window.
                /// @param WinPosition The position of the window.
                /// @param WimSize The size of the window.
                /// @param ButPosition The position of the accompanying button.
                /// @param ButSize The size of the accompanying button.
                virtual MenuWindow* CreateChildMenuWindow(ConstString& Name, Vector2 WinPosition, Vector2 WinSize, Vector2 ButPosition, Vector2 ButSize);
                /// @brief Gets an already created menu window by name.
                /// @return Returns a pointer to the menu window of the specified name.
                virtual MenuWindow* GetChildMenuWindow(ConstString& Name);
                /// @brief Gets an already created menu window by index.
                /// @return Returns a pointer to the menu window at the specified index.
                virtual MenuWindow* GetChildMenuWindow(Whole Index);
                /// @brief Gets the number of menu windows created and stored in this class.
                /// @return Returns the number of menu windows this class is storing.
                virtual Whole GetNumChildMenuWindows();
                /// @brief Destroys a menu window.
                /// @param ToBeDestroyed Pointer to the menu window you want destroyed.
                virtual void DestroyChildMenuWindow(MenuWindow* ToBeDestroyed);
        };
    }
}

#endif
