OGRE: Ogre::Radian Class Reference - OGRE Documentation
Ogre::Radian Class Reference
[Math]
Wrapper class which indicates a given angle value is in Radians.
#include <OgreMath.h>
Public Member Functions
Radian (Real r=0)
Radian (const Degree &d)
Radian & operator= (const Real &f)
Radian & operator= (const Radian &r)
Radian & operator= (const Degree &d)
Real valueDegrees () const
Real valueRadians () const
Real valueAngleUnits () const
const Radian & operator+ () const
Radian operator+ (const Radian &r) const
Radian operator+ (const Degree &d) const
Radian & operator+= (const Radian &r)
Radian & operator+= (const Degree &d)
Radian operator- () const
Radian operator- (const Radian &r) const
Radian operator- (const Degree &d) const
Radian & operator-= (const Radian &r)
Radian & operator-= (const Degree &d)
Radian operator* (Real f) const
Radian operator* (const Radian &f) const
Radian & operator*= (Real f)
Radian operator/ (Real f) const
Radian & operator/= (Real f)
bool operator< (const Radian &r) const
bool operator<= (const Radian &r) const
bool operator== (const Radian &r) const
bool operator!= (const Radian &r) const
bool operator>= (const Radian &r) const
bool operator> (const Radian &r) const
Private Attributes
Real mRad
Friends
_OgreExport friend std::ostream & operator<< (std::ostream &o, const Radian &v)
Detailed Description
Wrapper class which indicates a given angle value is in Radians.
Remarks:
Radian values are interchangeable with Degree values, and conversions will be done automatically between them.
Definition at line 46 of file OgreMath.h.
Constructor & Destructor Documentation
Ogre::Radian::Radian (Real r = 0) [explicit]
Definition at line 51 of file OgreMath.h.
Referenced by Ogre::Math::Abs(), Ogre::Math::ATan(), Ogre::Math::ATan2(), operator*(), operator+(), operator-(), operator/(), Ogre::Math::Sign(), and Ogre::Math::Sqrt().
Member Function Documentation
Radian& Ogre::Radian::operator= (const Real & f)
Definition at line 53 of file OgreMath.h.
References mRad.
Radian& Ogre::Radian::operator= (const Radian & r)
Definition at line 54 of file OgreMath.h.
References mRad.
Real Ogre::Radian::valueRadians () const
Definition at line 58 of file OgreMath.h.
References mRad.
Referenced by Ogre::Math::Abs(), Ogre::Math::Cos(), Ogre::Vector3::directionEquals(), Ogre::operator*(), Ogre::operator/(), Ogre::AnimableValue::setAsBaseValue(), Ogre::Math::Sign(), Ogre::Math::Sin(), Ogre::Math::Sqrt(), and Ogre::Math::Tan().
const Radian& Ogre::Radian::operator+ () const
Definition at line 61 of file OgreMath.h.
Radian Ogre::Radian::operator+ (const Radian & r) const
Definition at line 62 of file OgreMath.h.
References mRad, and Radian().
Radian& Ogre::Radian::operator+= (const Radian & r)
Definition at line 64 of file OgreMath.h.
References mRad.
Radian Ogre::Radian::operator- () const
Definition at line 66 of file OgreMath.h.
References mRad, and Radian().
Radian Ogre::Radian::operator- (const Radian & r) const
Definition at line 67 of file OgreMath.h.
References mRad, and Radian().
Radian& Ogre::Radian::operator-= (const Radian & r)
Definition at line 69 of file OgreMath.h.
References mRad.
Radian Ogre::Radian::operator* (Real f) const
Definition at line 71 of file OgreMath.h.
References mRad, and Radian().
Radian Ogre::Radian::operator* (const Radian & f) const
Definition at line 72 of file OgreMath.h.
References mRad, and Radian().
Radian& Ogre::Radian::operator*= (Real f)
Definition at line 73 of file OgreMath.h.
References mRad.
Radian Ogre::Radian::operator/ (Real f) const
Definition at line 74 of file OgreMath.h.
References mRad, and Radian().
Radian& Ogre::Radian::operator/= (Real f)
Definition at line 75 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator< (const Radian & r) const
Definition at line 77 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator<= (const Radian & r) const
Definition at line 78 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator== (const Radian & r) const
Definition at line 79 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator!= (const Radian & r) const
Definition at line 80 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator>= (const Radian & r) const
Definition at line 81 of file OgreMath.h.
References mRad.
bool Ogre::Radian::operator> (const Radian & r) const
Definition at line 82 of file OgreMath.h.
References mRad.
Friends And Related Function Documentation
_OgreExport friend std::ostream& operator<< (std::ostream & o, const Radian & v) [friend]
Definition at line 85 of file OgreMath.h.
Member Data Documentation
Real Ogre::Radian::mRad [private]
Definition at line 48 of file OgreMath.h.
Referenced by operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), valueAngleUnits(), valueDegrees(), and valueRadians().
The documentation for this class was generated from the following file:
OgreMath.h
Copyright © 2008 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 2.5 License.
Last modified Sat Apr 24 18:03:12 2010