OGRE: Ogre::ConstMapRange< T > Struct Template Reference - OGRE Documentation
Ogre::ConstMapRange< T > Struct Template Reference
Predefined type.
#include <OgreIteratorRange.h>
Public Types
typedef T iterator
typedef to fulfill container interface
typedef T const_iterator
typedef to fulfill container interface
typedef iterator_range< T > type
defines the real used type
Public Member Functions
ConstMapRange (const T &c)
Constructor.
ConstMapRange (typename T::iterator b, typename T::iterator e)
Constructor.
ConstMapRange (typename T::const_iterator b, typename T::const_iterator e)
Constructor.
ConstMapRange (const MapRange< T > &rhs)
Constructor.
bool operator== (const ConstMapRange &rhs) const
comparison operator for equality
bool operator!= (const ConstMapRange &rhs) const
comparison operator for inequality
T begin () const
access to the begin of the range
T end () const
access to the end of the range
bool empty () const
informs if there are any elements in the range
bool equal (const iterator_range &other) const
comparison for equality
bool operator== (const iterator_range &rhs) const
comparison operator for equality
bool operator!= (const iterator_range &rhs) const
comparison operator for inequality
Detailed Description
template<typename T>
struct Ogre::ConstMapRange< T >
Predefined type.
Parameters:
T iterator type
compatility class for ConstMapIterator
Definition at line 270 of file OgreIteratorRange.h.
Member Typedef Documentation
template<typename T> typedef T Ogre::iterator_range< T >::iterator [inherited]
typedef to fulfill container interface
Note:
there is no distinction between const_iterator and iterator.
Definition at line 91 of file OgreIteratorRange.h.
template<typename T> typedef T Ogre::iterator_range< T >::const_iterator [inherited]
typedef to fulfill container interface
Note:
there is no distinction between const_iterator and iterator.
Definition at line 99 of file OgreIteratorRange.h.
template<typename T> typedef iterator_range<T> Ogre::iterator_range< T >::type [inherited]
defines the real used type
type will be defined as Ogre::iterator_range if not used with boost
otherwise the type will be boost::iterator_range
Definition at line 106 of file OgreIteratorRange.h.
Constructor & Destructor Documentation
template<typename T> Ogre::ConstMapRange< T >::ConstMapRange (const T & c)
Constructor.
Remarks:
Provide a container to initialise.
Definition at line 277 of file OgreIteratorRange.h.
template<typename T> Ogre::ConstMapRange< T >::ConstMapRange (typename T::iterator b, typename T::iterator e)
Constructor.
Remarks:
Provide a start and end iterator to initialise.
Definition at line 285 of file OgreIteratorRange.h.
template<typename T> Ogre::ConstMapRange< T >::ConstMapRange (typename T::const_iterator b, typename T::const_iterator e)
Constructor.
Remarks:
Provide a start and end const_iterator to initialise.
Definition at line 293 of file OgreIteratorRange.h.
template<typename T> Ogre::ConstMapRange< T >::ConstMapRange (const MapRange< T > & rhs)
Constructor.
Remarks:
Provide a MapRange to initialise.
Definition at line 301 of file OgreIteratorRange.h.
Member Function Documentation
template<typename T> bool Ogre::ConstMapRange< T >::operator== (const ConstMapRange< T > & rhs) const
comparison operator for equality
Definition at line 306 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
template<typename T> bool Ogre::ConstMapRange< T >::operator!= (const ConstMapRange< T > & rhs) const
comparison operator for inequality
Definition at line 308 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
template<typename T> T Ogre::iterator_range< T >::begin () const [inherited]
access to the begin of the range
Definition at line 66 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin.
template<typename T> T Ogre::iterator_range< T >::end () const [inherited]
access to the end of the range
Definition at line 69 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mEnd.
template<typename T> bool Ogre::iterator_range< T >::empty () const [inherited]
informs if there are any elements in the range
Definition at line 72 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin, and Ogre::iterator_range< T >::mEnd.
template<typename T> bool Ogre::iterator_range< T >::equal (const iterator_range< T > & other) const [inherited]
comparison for equality
Definition at line 75 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin, and Ogre::iterator_range< T >::mEnd.
Referenced by Ogre::ConstMapRange< T >::operator!=(), Ogre::MapRange< T >::operator!=(), Ogre::ConstVectorRange< T >::operator!=(), Ogre::VectorRange< T >::operator!=(), Ogre::ConstMapRange< T >::operator==(), Ogre::MapRange< T >::operator==(), Ogre::ConstVectorRange< T >::operator==(), Ogre::VectorRange< T >::operator==(), and Ogre::iterator_range< T >::operator==().
template<typename T> bool Ogre::iterator_range< T >::operator== (const iterator_range< T > & rhs) const [inherited]
comparison operator for equality
Definition at line 79 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
Referenced by Ogre::iterator_range< T >::operator!=().
template<typename T> bool Ogre::iterator_range< T >::operator!= (const iterator_range< T > & rhs) const [inherited]
comparison operator for inequality
Definition at line 83 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::operator==().
The documentation for this struct was generated from the following file:
OgreIteratorRange.h
Copyright © 2008 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 2.5 License.
Last modified Sat Apr 24 18:02:50 2010