OGRE: Ogre::NedPoolingImpl Class Reference - OGRE Documentation
Ogre::NedPoolingImpl Class Reference
[Memory]
Non-templated utility class just to hide nedmalloc.
#include <OgreMemoryNedPooling.h>
Static Public Member Functions
static void * allocBytes (size_t count, const char *file, int line, const char *func)
static void deallocBytes (void *ptr)
static void * allocBytesAligned (size_t align, size_t count, const char *file, int line, const char *func)
static void deallocBytesAligned (size_t align, void *ptr)
Detailed Description
Non-templated utility class just to hide nedmalloc.
Definition at line 45 of file OgreMemoryNedPooling.h.
Member Function Documentation
static void* Ogre::NedPoolingImpl::allocBytes (size_t count, const char * file, int line, const char * func) [static]
Referenced by Ogre::NedPoolingPolicy::allocateBytes().
static void* Ogre::NedPoolingImpl::allocBytesAligned (size_t align, size_t count, const char * file, int line, const char * func) [static]
Referenced by Ogre::NedPoolingAlignedPolicy< align >::allocateBytes().
static void Ogre::NedPoolingImpl::deallocBytes (void * ptr) [static]
Referenced by Ogre::NedPoolingPolicy::deallocateBytes().
static void Ogre::NedPoolingImpl::deallocBytesAligned (size_t align, void * ptr) [static]
Referenced by Ogre::NedPoolingAlignedPolicy< align >::deallocateBytes().
The documentation for this class was generated from the following file:
OgreMemoryNedPooling.h
Copyright © 2008 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Wed Nov 3 2010 19:24:56