OGRE: Ogre::LinearResampler_Float32 Struct Reference - OGRE Documentation
Ogre::LinearResampler_Float32 Struct Reference
[Image]
#include <OgreImageResampler.h>
Static Public Member Functions
static void scale (const PixelBox &src, const PixelBox &dst)
Detailed Description
Definition at line 177 of file OgreImageResampler.h.
Member Function Documentation
static void Ogre::LinearResampler_Float32::scale (const PixelBox & src, const PixelBox & dst) [static]
Definition at line 178 of file OgreImageResampler.h.
References ACCUM3, ACCUM4, Ogre::Box::back, Ogre::Box::bottom, Ogre::PixelBox::data, Ogre::PixelBox::format, Ogre::Box::front, Ogre::Box::getDepth(), Ogre::Box::getHeight(), Ogre::PixelUtil::getNumElemBytes(), Ogre::PixelBox::getRowSkip(), Ogre::PixelBox::getSliceSkip(), Ogre::Box::getWidth(), Ogre::Box::left, Ogre::Box::right, and Ogre::Box::top.
The documentation for this struct was generated from the following file:
OgreImageResampler.h
Copyright © 2008 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Wed Nov 3 2010 19:25:04