#!/bin/bash
# Appends items at the top of a file
 
E_BADARGS=1

if [ ! -n "$2" ]
then
  echo "Usage: `basename $0` NewHeaderFile OldHeaderFile SourceFile1 SourceFile2 SourceFile3 etc."
  exit $E_BADARGS
fi 



OldLicenseLength = `grep "This should not be found on any lineasdfasdfasdfasdf" $2 -vc`


$1 > temp

#NExt line needs to skip the first OldLicenseLength lines then copy that into the files with the new license
cat $3 >> temp

#rm -f $2
#mv temp $2
